name: 'Line Counter'
description: 'A custom GitHub Action to count the number of lines in a text file using a public Docker image'

inputs:
  file_path:
    description: 'The path to the text file'
    required: true

outputs:
  line_count:
    description: 'The number of lines in the file'

runs:
  using: 'docker'
  image: 'alpine:3.12'
  entrypoint: ["/bin/sh", "/entrypoint.sh"]
  args:
    - ${{ inputs.file_path }}
