name: 'Hello World Shell Action'
description: 'Greet someone and tell them the time.'
inputs:
  who-to-greet:
    description: 
    default: 'world'
    required: true
    type: string
outputs:
  time:
    description: 'The time the greeting was made'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
