name: 'Docker Container Action with Existing Image'
description: 'A GitHub Action that uses an existing Docker image and installs Python dependencies'

inputs:
  python_dependencies:
    description: 'Python dependencies to install'
    required: true
outputs:
  python_dependencies_installed:
    description: 'Indicates whether Python dependencies were successfully installed'
runs:
  using: 'docker'
  image: 'docker://docker:stable-dind'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
      # Start Docker daemon
      dockerd > /dev/null 2>&1 &
      sleep 5

      # Run the container with the repository mounted and execute the script
      docker run --rm -v $GITHUB_WORKSPACE:/workspace -w /workspace ubuntu:latest /workspace/install_dependencies.sh "${{ inputs.python_dependencies }}"
