name: 'Docker Container Action with Existing Image'
description: 'A GitHub Action that uses an existing Docker image and installs Python dependencies'

inputs:
  python_dependencies:
    description: 'Python dependencies to install'
    required: true
outputs:
  python_dependencies_installed:
    description: 'Indicates whether Python dependencies were successfully installed'
runs:
  using: 'docker'
  image: 'docker://stable' # Using a Docker image with Docker installed
  entrypoint: '/bin/bash'
  args:
    - '-c'
    - |
      docker run -v $GITHUB_WORKSPACE/python:/scripts ubuntu:latest /scripts/entrypoint.sh "${{ inputs.python_dependencies }}"
