name: 'Install Python Dependencies'
description: 'A GitHub Action that installs Python dependencies'

inputs:
  python_dependencies:
    description: 'Python dependencies to install'
    required: true
  workspace:
    description: 'Path to the GitHub workspace directory'
    required: false
    default: '${{ github.workspace }}'

outputs:
  python_dependencies_installed:
    description: 'Indicates whether Python dependencies were successfully installed'

runs:
  using: 'docker'
  image: 'docker://ubuntu:latest'
  entrypoint: '/entrypoint.sh'

container:
  image: 'ubuntu:latest'
  options: '--privileged'  # Add the --privileged flag to enable access to Docker socket
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket into the container
    - '${{ github.workspace }}:/workspace'
